apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: spring-petclinic
spec:
  type: NodePort     # Change to LoadBalancer if using cloud provider
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  selector:
    app: petclinic