apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: ghcr.io/user-raghava/spring-petclinic-lab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/petclinic
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: petclinic-db-credentials
                  key: password
          livenessProbe:
              httpGet:
                path: /actuator/health/liveness
                port: 8080
              initialDelaySeconds: 60     # was probably 30 or less
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 6
          readinessProbe:
              httpGet:
                path: /actuator/health/readiness
                port: 8080
              initialDelaySeconds: 45     # give more time to connect to Postgres
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 6
          startupProbe:                 # Add this - very helpful for Spring Boot
              httpGet:
                path: /actuator/health/liveness
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
              failureThreshold: 30        # allow up to 5 minutes for startup
          
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"